### ISSUE TITLE
make it full

### ISSUE THREAD

**Issue by Zebra67** [joseph27/SmartRingtoneMakerLTE#1]
plz make it full version , some option are very good in full version like buy pro version popup .and other settings

**Comment by joseph27** [comment]
well, that is not an issue to be fixed it's a suggestion. the whole project was not meant to be for free, but I decided to share some of the key features with other developers if you are interested in the full range of the premium features then please purchase the licenses, I have spent months developing this application and I have decided to share these features here on GitHub as gratitude because of using some open source libraries in the project.

**Comment by Zebra67** [comment]
then plz make sample only for inbuilt purchase, I could not find any proper sample for inbuilt purchase

**Comment by Zebra67** [comment]
one thing more on which site these screenshot are created
